class AuthStatus:
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USERNAME_TAKEN = "USERNAME_TAKEN"
    TOKEN_INVALID = "TOKEN_INVALID"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_WRONG_TYPE = "TOKEN_WRONG_TYPE"

    # OAuth (Google / GitHub)
    OAUTH_PROVIDER_ERROR = "OAUTH_PROVIDER_ERROR"
    OAUTH_EMAIL_MISSING = "OAUTH_EMAIL_MISSING"
    OAUTH_ACCOUNT_LINKED = "OAUTH_ACCOUNT_LINKED"

    # Profile
    PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS"
    AVATAR_UPDATE_SUCCESS = "AVATAR_UPDATE_SUCCESS"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"