class AuthStatus:
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USERNAME_TAKEN = "USERNAME_TAKEN"
    TOKEN_INVALID = "TOKEN_INVALID"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_WRONG_TYPE = "TOKEN_WRONG_TYPE"

    # OAuth (Google / GitHub)
    OAUTH_PROVIDER_ERROR = "OAUTH_PROVIDER_ERROR"
    OAUTH_EMAIL_MISSING = "OAUTH_EMAIL_MISSING"
    OAUTH_ACCOUNT_LINKED = "OAUTH_ACCOUNT_LINKED"

    # Profile
    PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS"
    AVATAR_UPDATE_SUCCESS = "AVATAR_UPDATE_SUCCESS"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    RATE_LIMITED = "RATE_LIMITED"

    # RBAC / admin (see services/admin/authz.py)
    ACCOUNT_BANNED = "ACCOUNT_BANNED"
    INSUFFICIENT_ROLE = "INSUFFICIENT_ROLE"
    MASTER_PROTECTED = "MASTER_PROTECTED"
    ADMIN_TARGET_FORBIDDEN = "ADMIN_TARGET_FORBIDDEN"
    INVALID_ROLE_TARGET = "INVALID_ROLE_TARGET"
    TARGET_NOT_FOUND = "TARGET_NOT_FOUND"
    BAN_SUCCESS = "BAN_SUCCESS"
    UNBAN_SUCCESS = "UNBAN_SUCCESS"
    ROLE_CHANGE_SUCCESS = "ROLE_CHANGE_SUCCESS"
    ADMIN_ACTION_SUCCESS = "ADMIN_ACTION_SUCCESS"
    # Password auth / OTP
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    OTP_SENT = "OTP_SENT"
    OTP_INVALID = "OTP_INVALID"
    REGISTER_SUCCESS = "REGISTER_SUCCESS"
    PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS"
    TOKEN_REFRESH_SUCCESS = "TOKEN_REFRESH_SUCCESS"